### ISSUE TITLE
Creating a neither_to_nor_from_ds frame

### ISSUE THREAD

**Issue by ProfFan** [Frostie314159/ieee80211-rs#13]
How could one create a non-to-from-DS data frame? Cause this is the only type of data frame that I can get `esp_wifi_tx_80211` to accept...

for example:
```
    let frame_buf = [
        0x48u8, 0x03, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xE8, 0x65, 0xD4, 0xCB, 0x74,
        0x19, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x60, 0x94, 0xE8, 0x65, 0xD4, 0xCB, 0x74, 0x1C,
        0x26, 0xB9, 0x0D, 0x02, 0x7D, 0x13, 0x00, 0x00, 0x01, 0xE8, 0x65, 0xD4, 0xCB, 0x74, 0x1C,
        0x00, 0x00, 0x26, 0xB9, 0x00, 0x00, 0x00, 0x00,
    ];
```

**Comment by ProfFan** [comment]
I tried the builder but can't get across the type system.

**Comment by Frostie314159** [comment]
Yeah the builder is a bit broken. I'll look into it. 
Regarding the esp32: The API accepts any frame, if it meets the restrictions set in the docs of the c version.

**Comment by Frostie314159** [comment]
This should be fixed now.

**Comment by ProfFan** [comment]
Thank you! Let me check if it works here.

**Comment by Frostie314159** [comment]
Btw. If you need to be able to transmit frames without restrictions, you could try porting this https://github.com/Frostie314159/esp32-80211-tx to rust.

**Comment by ProfFan** [comment]
I think the problem is `esp-hal`'s current sniffer requires AP/STA mode and this adds a lot of restrictions. I created an issue there.

**Comment by Frostie314159** [comment]
This isn't an issue with esp-hal, but much rather the proprietary blob. Espressif could have done this differently, but they sadly didn't. Maybe, once we have an open Mac implementation, we can sidestep any and all restrictions.

**Comment by ProfFan** [comment]
#14

**Comment by Frostie314159** [comment]
Is this completed?

**Comment by Frostie314159** [comment]
Funny story: While I was writing the test for data frame RW I found another inconsistency in the builder. I reviewed the entire builder code again and it should all be ironed out now.

**Comment by Frostie314159** [comment]
I'm gonna close this, since I pushed out v0.5.0, which resolves the issue.
