### ISSUE TITLE
Benchmark error

### ISSUE THREAD

**Issue by zamazan4ik** [Frostie314159/ieee80211-rs#2]
Hi!

Right now after calling from the project's root the `cargo bench` command, I get the following error:
```
cargo bench

   Compiling ieee80211 v0.2.2 (/home/zamazan4ik/open_source/ieee80211-rs)
error[E0583]: file not found for module `vht`
  --> src/elements/mod.rs:25:1
   |
25 | pub mod vht;
   | ^^^^^^^^^^^^
   |
   = help: to create the module `vht`, create file "src/elements/vht.rs" or "src/elements/vht/mod.rs"
   = note: if there is a `mod vht` elsewhere in the crate already, import it with `use crate::...` instead

For more information about this error, try `rustc --explain E0583`.
error: could not compile `ieee80211` (lib test) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `ieee80211` (lib) due to 1 previous error
```

Expected behavior: the benchmark executes successfully.

OS: Fedora 40
Rustc version: 1.79.0
ieee80211-rs version: `master` branch, `b2f8fef18a071d1e297bb2f660153a434e12df76` commit

**Comment by Frostie314159** [comment]
Hi, 
thanks for the issue!
This was an artifact of me implementing vht elements in the background and accidentally pushing the wrong file.
I also haven't updated these values in a while.
Will fix it right away.

**Comment by Frostie314159** [comment]
Should be fixed in latest commit.

**Comment by zamazan4ik** [comment]
Thanks! Just checked the updated version - the issue is fixed.

**Comment by Frostie314159** [comment]
I added a CI step, to test the benchmark.
