### ISSUE TITLE
Can't decode beacon frame

### ISSUE THREAD

**Issue by kevinbader** [Frostie314159/ieee80211-rs#7]
Hi,

thanks for working on this, I'd like to use this in my pet project :) Unfortunately, I struggle to do the most basic thing: reading a beacon to see the SSID.

I'm using a .pcap file that contains a single packet that, at least according to Wireshark, contains a beacon frame:

![image](https://github.com/user-attachments/assets/51cbec50-a49c-45f3-b932-2788c18fd8de)

I parse this using [`PcapReader` of the `pcap-file` crate](https://docs.rs/pcap-file/latest/pcap_file/pcap/struct.PcapReader.html):

```rust
fn buffered_file_reader(path: &Path) -> impl Read {
    std::io::BufReader::new(std::fs::File::open(path).unwrap())
}

fn dump_pcap(pcap_file: PathBuf) -> eyre::Result<()> {
    let reader = buffered_file_reader(&pcap_file);
    let mut reader = PcapReader::new(reader).unwrap();
    while let Some(pkt) = reader.next_packet() {
        let data = pkt?.data;
```

### Attempt 1 with `ieee80211` 0.3.1

I pattern-match my way to the beacon frame type:

```rust
        let frame: IEEE80211Frame = data
            .pread(0)
            .map_err(|e| eyre::eyre!("failed to parse pcap file at {pcap_file:?}: {e}"))?;
        debug!("{frame:#?}");
        match frame {
            IEEE80211Frame::Management(frame) => match frame.body {
                ManagementFrameBody::AssociationRequest(_) => todo!(),
                ManagementFrameBody::AssociationResponse(_) => todo!(),
                ManagementFrameBody::ProbeRequest(_) => todo!(),
                ManagementFrameBody::ProbeRespone(_) => todo!(),
                ManagementFrameBody::Beacon(beacon) => {
                    debug!("{beacon:#?}");
                }
                ManagementFrameBody::ATIM => todo!(),
                ManagementFrameBody::Disassociation(_) => todo!(),
                ManagementFrameBody::Deauthentication(_) => todo!(),
                ManagementFrameBody::Action(_) => todo!(),
                ManagementFrameBody::ActionNoACK(_) => todo!(),
                ManagementFrameBody::Unknown { subtype, body } => todo!(),
            },
            IEEE80211Frame::Control(_) => todo!(),
            IEEE80211Frame::Data(_) => todo!(),
        };
```

However, instead of `Beacon` it matches on `AssociationRequest`. Is this a bug?

### Attempt 2 with `ieee80211` at [current master](https://github.com/Frostie314159/ieee80211-rs/tree/93ef940633bf832389f4e40db7a23cafa3f3ffb8)

I've wanted to use [`match_frames!` according to the example](https://github.com/Frostie314159/ieee80211-rs/blob/93ef940633bf832389f4e40db7a23cafa3f3ffb8/examples/match_frames.rs#L5), but it imports `scroll::Pread` instead of `ieee80211::scroll::Pread`, so I expanded and fixed the generated code to:

```rust
        {
            use ieee80211::scroll::Pread;
            use ieee80211::{common::FrameControlField, IEEE80211Frame};
            let fcf = data.pread(0).map(FrameControlField::from_bits);
            if let Ok(fcf) = fcf {
                'matched: {
                    if (<BeaconFrame as IEEE80211Frame>::TYPE == fcf.frame_type())
                        || (<BeaconFrame as IEEE80211Frame>::MATCH_ONLY_TYPE
                            && <BeaconFrame as IEEE80211Frame>::TYPE.type_matches(fcf.frame_type()))
                    {
                        break 'matched data.pread::<BeaconFrame>(0).map(|beacon_frame| {
                            println!("SSID: {}", beacon_frame.body.ssid().unwrap());
                        });
                    }
                    Err(ieee80211::scroll::Error::BadInput {
                        size: 0,
                        msg: "Frame type not matched.",
                    })
                }
            } else {
                Err(fcf.unwrap_err())
            }
            .unwrap()
        };
```

This doesn't recognize the beacon frame either and unwraps the error `BadInput { size: 0, msg: "Frame type not matched." }`.

What am I missing?

**Comment by Frostie314159** [comment]
https://github.com/Frostie314159/grace/blob/master/src%2Fgrace.rs#L194 this is an example from grace. It just ignores the header, which is probably fine for your project.

**Comment by Frostie314159** [comment]
Let me know what you think of the new approach with`match_frames!`. I haven't been able to test it much yet. My primary motivation was, not having one monolithic enum, taking large amounts of stack space.

**Comment by kevinbader** [comment]
Thanks for pointing me to radiotap, I didn't know about it. I'll play around a bit more with `match_frames!` and let you know once I understand all this machinery a bit better :)

**Comment by Frostie314159** [comment]
No problem, if you have any questions, feel free to ask. The machinery for match frames is only fully implemented for management frames, data and control are yet to come.

**Comment by kevinbader** [comment]
Okay I have one more question :) Wireshark shows the Radiotap header you've mentioned, but the SSID is actually part of the "Wireless Management" section:

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/29c99bb2-ac92-4abb-9223-5d96d1793ca9">

According to [the example](https://github.com/Frostie314159/ieee80211-rs/blob/master/examples/match_frames.rs), the SSID should be part of the beacon... does this mean, `IEEE 802.11 Wireless Management` is part of the beacon, too? When I export the beacon part as bytes to a file and read it the same way you do in the example, I get the following error: `TooBig { size: 8, len: 0 }`.

**Comment by Frostie314159** [comment]
Wireshark shows the header and the body separately. Practically speaking, it's all the beacon frame. The header is pretty much the same across all management frames and each different body usually introduces a fixed sized header, followed by a series of elements. One of which is the ssid. Could you send me the frame binary and the code you used for reading and writing?

**Comment by kevinbader** [comment]
Ahh, I see - indeed, exporting both "beacon frame" and "wireless management" and `cat`ing them into one binary, it parses just fine. So to summarize, in order to get to the SSID from a .pcap file, I need to do the following:

1. parse the .pcap, get a packet
2. from the packet's `data`, strip the radiotap header to get the frame (using your `rtap` crate)
3. parse this frame with `match_frames`

**Comment by Frostie314159** [comment]
Pretty much, yes. You can also select the frame layer in Wireshark and click show packet bytes, then advance the starting point beyond the length of the radiotap header and then save as raw binary. If you know you're getting beacon frames, you can also parse the beacon frame directly with pread. There's an example with that in the elements example
